version: '3.4'
networks:
  dockerapi-dev:
    driver: bridge
volumes:
  pgdata:

services:
  postgres_image:
    image: postgres:latest
    ports: 
      - "5432:5432"
    container_name: postgres_image_container
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "accountdb"
    networks:
      - dockerapi-dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  account_ms:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION_STRING: "Host=postgres_image;port=5432;Database=accountdb;Username=admin;Password=admin"
    ports:
      - "8000:80"
    depends_on:
      - "postgres_image"
    container_name: account_image_container
    networks:
      - dockerapi-dev